name: Build and Test on Linux

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  proc_num: $(nproc)

jobs:
  gcc-compile-with-make:
    runs-on: ubuntu-24.04 # https://github.com/actions/runner-images
    steps:
    - uses: actions/checkout@v7
    - uses: ./.github/actions/install-essential-dependences
    - uses: ./.github/actions/init-make-config
      with:
        options: --cc=gcc --cxx=g++
    - name: compile
      run: |
           make -j ${{env.proc_num}}

  gcc-compile-with-cmake:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v7
    - uses: ./.github/actions/install-essential-dependences
    - name: cmake 
      run: |
           export CC=gcc && export CXX=g++
           mkdir build
           cd build
           cmake ..
    - name: compile
      run: |
           cd build
           make -j ${{env.proc_num}}

  gcc-compile-with-bazel:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v7
    - name: install dependences
      run: |
           sudo apt-get update
           sudo apt-get install libibverbs-dev
    - name: compile
      run: |
           export CC=gcc && export CXX=g++
           bazel build -j ${{env.proc_num}} -c opt --copt -DHAVE_ZLIB=1 //...

  gcc-compile-with-make-all-options:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v7
    - uses: ./.github/actions/install-all-dependences
    - uses: ./.github/actions/init-make-config
      with:
        options: --cc=gcc --cxx=g++ --with-thrift --with-glog
    - name: compile
      run: |
           make -j ${{env.proc_num}}

  gcc-compile-with-cmake-all-options:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v7
    - uses: ./.github/actions/install-all-dependences
    - name: cmake 
      run: |
           export CC=gcc && export CXX=g++
           mkdir build
           cd build
           cmake -DWITH_MESALINK=OFF -DWITH_GLOG=ON -DWITH_THRIFT=ON ..
    - name: compile
      run: |
           cd build
           make -j ${{env.proc_num}}

  gcc-compile-with-bazel-all-options:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v7
    - name: install dependences
      run: |
           sudo apt-get update
           sudo apt-get install libibverbs-dev
    - name: compile
      run: |
           export CC=gcc && export CXX=g++
           bazel build -j 12 -c opt --define with_mesalink=false --define with_glog=true --define with_thrift=true --copt -DHAVE_ZLIB=1 //...

  gcc-unittest:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v7
    - uses: ./.github/actions/install-essential-dependences
    - name: install test dependencies
      run: sudo apt-get install -y gdb libgtest-dev
    - uses: ./.github/actions/init-make-config
      with:
        options: --cc=gcc --cxx=g++
    - name: compile tests
      run: |
           cd test
           make -j ${{env.proc_num}}
    - name: run tests
      run: |
           cd test
           sh ./run_tests.sh
